### ISSUE TITLE
[bug?]FERNNPRFace中SDFFaceDiffuse在直射光角度y轴取180-270度的渲染问题

### ISSUE THREAD

**Issue by Unarimit** [FernRP/FernRP#2]
我用这个shader来渲染角色脸部，在标题所说的直射光环境下，会导致脸部一直是黑的

我尝试修改一些逻辑发现：NPRLighting中有一个`(faceArea+90.0)`的神秘操作，我把`+90`删掉之后，就不会出现这种情况。
https://github.com/FernRP/FernRP/blob/698bb410ef5c61f8565c47488dc44da707dca547/Runtime/ShaderLibrary/NPRLighting.hlsl#L88

unity场景复现问题，左边白毛模型脸部使用SDFFaceDiffuse，右边粉毛模型使用CelDiffuce做对照
![angle200](https://github.com/FernRP/FernRP/assets/50516501/bed882c4-e940-4b5d-b1f6-d002341ea6b4)

删去`+90`之后
![angle200_without90](https://github.com/FernRP/FernRP/assets/50516501/d92a7932-c568-4496-8239-c60e22fec6c2)

**Comment by DJ-Huang** [comment]
时间太久，我也忘了+90是为何，等我有空测测。。

**Comment by DJ-Huang** [comment]
+90 只是为了增加脸部角度的范围，实际上可以不加，我已经去掉，如果确实需要增加范围，可以直接调整材质中的Face Angle Range（之前叫Face Area） 参数
![image](https://github.com/FernRP/FernRP/assets/18584942/bef6889d-e92e-4697-8f76-57de697916da)
